# https://docs.github.com/cn/actions/automating-builds-and-tests/building-and-testing-python

name: Update papers

# 国际标准时间2点（北京时间10点）
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: ./install.sh

      - name: Push articles
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          S2API_KEY: ${{ secrets.S2API_KEY }}

          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_BOT: ${{ secrets.FEISHU_BOT }}
          FEISHU_BITABLE_VEHICLE: ${{ secrets.FEISHU_BITABLE_VEHICLE }}
          FEISHU_BITABLE_ANDROID: ${{ secrets.FEISHU_BITABLE_ANDROID }}
          FEISHU_BITABLE_LINUX: ${{ secrets.FEISHU_BITABLE_LINUX }}

          WOLAI_APP_ID: ${{ secrets.WOLAI_APP_ID }}
          WOLAI_APP_SECRET: ${{ secrets.WOLAI_APP_SECRET }}
          WOLAI_DATABASE_VEHICLE: ${{ secrets.WOLAI_DATABASE_VEHICLE }}
          WOLAI_DATABASE_ANDROID: ${{ secrets.WOLAI_DATABASE_ANDROID }}
          WOLAI_DATABASE_LINUX: ${{ secrets.WOLAI_DATABASE_LINUX }}
        run: python3 openccf.py --year 2022:2024 --rule NIS:all:all:all --bot wolai

      - name: Commit
        run: |
          git diff
          git config --global user.email firmianay@gmail.com
          git config --global user.name firmianay
          git add data
          git commit -m "Update `TZ=':Asia/Shanghai' date +' %Y-%m-%d %H:%m:%S'`" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}

  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 7
